### ISSUE TITLE
Resources are doubled in index.html with plugin

### ISSUE THREAD

**Issue by laurentschoelens** [jarlef/vite-plugin-preload#13]
Hi @jarlef 

Your plugin is just magic to help use preload / prefetch with vite.
I've just had one issue : if my ressources are with './' in link, they are doubled in the final index.html and loaded twice by browser.

Example (extract) of generated `index.html`
```html
    <link rel="modulepreload" crossorigin="" href="./assets/pdf-DyMWGzR2.js" />
    <link rel="stylesheet" crossorigin="" href="./assets/index-_rMpy4mS.css" />
...
    <link rel="modulepreload" href="assets/pdf-DyMWGzR2.js" />
...
    <link rel="modulepreload" href="assets/vendor-CIrZrXrV.js" />
...
    <link rel="stylesheet" href="assets/index-_rMpy4mS.css" />
```

As you can see, I've got `pdf-DyMWGzR2.js` twice in my declaration as well as `index-_rMpy4mS.css`

I'm pretty sure this issue comes because I use `base: './'` in my `vite.config.js`, which I can't remove.
Could you help fixing this issue ? My guess for fixing would be a special handling of resources starting with './' in the `getExistingLinks` function.

Thanks

**Comment by jarlef** [comment]
Thanks for reporting this. I have published a new version which normalizes the paths so that it would treat `./assets/pdf-DyMWGzR2.js` and `assets/pdf-DyMWGzR2.js` as the same asset.

**Comment by laurentschoelens** [comment]
I'll give a try and tell you if this works

**Comment by laurentschoelens** [comment]
I've installed the `"vite-plugin-preload": "^0.4.1"` but still facing the same issue.

I guess you should also apply the `normalize` to the `getExistingLinks` returned elements

**Comment by jarlef** [comment]
Try updating to version `0.4.2`

**Comment by laurentschoelens** [comment]
Thanks. I'll give a try and keep you updated

**Comment by laurentschoelens** [comment]
It works like a charm, many thanks for the quick fix 😄
